# Generated by Django 3.1.2 on 2020-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fruits', models.CharField(max_length=200)),
                ('Vegitables', models.CharField(max_length=200)),
                ('Meat_products', models.CharField(max_length=200)),
                ('Nuts', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreakFast', models.CharField(max_length=200)),
                ('Lunch', models.CharField(max_length=200)),
                ('Dinner', models.CharField(max_length=200)),
            ],
        ),
    ]
