# Generated by Django 3.1.2 on 2020-11-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='MealType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meals'),
        ),
    ]
