# Generated by Django 3.1.2 on 2020-11-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201114_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='Fruits',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='Meat_products',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='Nuts',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='Vegitables',
        ),
    ]
