# Generated by Django 3.1.2 on 2020-11-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201114_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='MealType',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('protien', models.IntegerField()),
                ('per_how_much_gram', models.IntegerField()),
                ('FoodType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.foodtype')),
                ('MealType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meals')),
            ],
        ),
    ]
